version: "3.8"

services:
    #1. A base de dadosm(o coracao do sistema)
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=webpass2334!
      - POSTGRES_DB=servidor_local
    ports:
      - "5432:5432"
    #volumes:
     # - postgres_data:/var/lib/postgresql/data

  api:
    build: . 
    # CONSTRUI O SERVIDOR A PARTIR DO DOCKERFILE
    environment:
      #- DATABASE_URL=postgresql://root:webpass2334!@db:5432/servidor-local
      - DB_PG_HOST=db
      - DB_PG_PORT=5432
      - DB_PG_NAME=servidor_local
      - DB_PG_USER=root
      - DB_PG_PASSWORD=webpass2334!
      - JWT_SECRET=fsjkfvhsduihjkcgdfjghdfghdcjkvhdfjkhcvnbjfghdfkjgnldfbjdfhguhfbjncvbhfghcvkjbnfdhgdhfçjvkjdhdfuhguidfhgcvjnbcvhbjfcngfjckbhdfughcjkbncvjkbhdkghcvkbncjkgfbhdvbcbvhcv.jvlkdfuvj"
      - PORT=8080
    ports:
     - "8080:8080"
    depends_on:
      - db
  k6_attacker:
    image: grafana/k6:latest
    volumes:
      - ./src:/app/src
    command: ["sleep", "infinity"]
    depends_on:
      - api
    ports:
      - "5665:5665"
    environment:
      - K6_WEB_DASHBOARD=true
    # - K6_WEB_DASHBOARD_HOST=0.0.0.0