services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: servidor_local
    ports:
      - "5432:5432"

  api:
    build: .
    #image: servidor-local
    environment:
      - DATABASE_URL=${DATABASE_URL:? Set DATABASE_URL}
      - DB_PG_HOST=${DB_PG:?Set DB_PG_HOST}
      - DB_PG_PORT=${DB_PG:?Set DB_PG_PORT}
      - DB_PG_NAME=${DB_PG:?Set DB_PG_NAME}
      - DB_PG_USER=${DB_PG:?Set DB_PG_USER}
      - DB_PG_PASSWORD=${DB_PG:?Set DB_PG_PASSWORD}
      - PORT=${DB_PG:?Set DB_PG_PORT}
      - JWT_SECRET=${DB_PG:?Set BD_PG_PORT}
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
  
  k6_attack:
    image: grafana/k6:latest
    volumes:
      - ./src:/app/src
    command: ["sleep", "infinity"]
    depends_on:
      - api
    ports:
      - "5665:5665"
    environment:
      - K6_WEB_DASHBOARD=true
      - K6_WEB_DASHBOARD_HOST=0.0.0.0

