
name: servidor-local-center
services:
  #serviços a serem executados
  db:
    #serviço de base de dados
    image: postgres:15 #imagem da base de dados
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Webpass2334!
      POSTGRES_DB: servidor_local
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  api:
    #serviço do servidor local
    build: . # Constrói a vossa API a partir do Dockerfile
    environment:
      #DATABASE_URL: "postgresql://root:Webpass2334!@db:5432/servidor-local"
      - DB_PG_HOST=db
      - DB_PG_USER=root
      - DB_PG_PORT=5432
      - DB_PG_NAME=servidor_local
      - DB_PG_PASSWORD=Webpass2334!
      - JWT_SECRET=fuiguifweu9qgerwiog3rg3r53erqoigepq
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  k6_attacker:
    #serviço de k6_attacker
    image: grafana/k6:latest #imagem de k6_attacker
    volumes:
      - ./src:/app/src
    command: [ "sleep", "infinity" ]
    depends_on:
      - api
    ports:
      - "5665:5665"
    environment:
      - K6_WEB_DASHBOARD=true
      # - K6_WEB_DASHBOARD_HOST: 0.0.0.0
