name: Auditoria Final

on:
  push:
    branches: ["main", "dev","kleber-dev"]
      

jobs:
  auditoria:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Iniciar Docker
        run: docker compose up -d db api

      - name: Esperar base de dados estar pronta
        run: sleep 10

      - name: Executar Auditoria k6
        run: docker compose run --rm k6 run /scripts/auditoria-final.js

      - name: Encerrar Containers
        if: always()
        run: docker compose down