name: Testes de Performance (K6)

on:
  push:
    branches: ["main", "dev"]

jobs:
  teste-attack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Levantar docker
        env:
          -DATABASE_URL=${{ secrets.DATABASE_URL }}
          - JWT_SECRET=${{ secrets.JWT_SECRET }}
          - PORT=${{ secrets.PORT }}
          - DB_PG_HOST=${{ secrets.DB_PG_HOST }}
          - DB_PG_PORT=${{ secrets.DB_PG_PORT }}
          - DB_PG_NAME=${{ secrets.DB_PG_NAME }}
          - DB_PG_USER=${{ secrets.DB_PG_USER }}
          - DB_PG_PASSWORD=${{ secrets.DB_PG_PASSWORD }}

        run: docker compose up -d de api

      - name: Esperar o db estar pronto
        run: sleep 10

      - name: Executar ataque do K6
        run:  docker compose run --rm --service-ports k6_attack run /app/src/script/teste-carga-login.js
