name: Testes de Performance (K6)

on:
  push:
    branches: ["main", "dev", "ismar-dev"]

jobs:
  test-attack:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: servidor-local # path to the folder with docker-compose.yml

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Levantar docker
        env:
          - DATABASE_URL= ${{secrets.DATABASE_URL}}
          - JWT_SECRET= ${{secrets.JWT_SECRET}}
          - PORT= ${{secrets.PORT}}
          - DB_PG_HOST= ${{secrets.DB_PG_HOST}}
          - DB_PG_PORT= ${{secrets.DB_PG_PORT}}
          - DB_PG_NAME= ${{secrets.DB_PG_NAME}}
          - DB_PG_USER= ${{secrets.DB_PG_USER}}
          - DB_PG_PASSWORD= ${{secrets.DB_PG_PASSWORD}}
        run: docker compose up -d db api

      - name: Esperar o db estar pronto
        run: sleep 10

      - name: Executar ataque do k6
        run: docker compose run --rm k6_attack run /app/src/script/teste-carga-servicos.js
 